### ISSUE TITLE
Does not add modernizr to destination

### ISSUE THREAD

**Issue by webdif** [ianllewellyn/modernizr-brunch#1]
Sorry to ask such a stupid question, but I was excited to see a brunch plugin for modernizr, and nothing happens when I try it :(

I add this config:

```
plugins:
        modernizr:
            destination: 'js/app.js'
            tests: [
                'csscalc'
                'cssanimations'
                'csstransforms3d'
            ]
```

But nothing is added to my `app.js`. Am I doing something wrong?
Thanks for your help.

**Comment by ianllewellyn** [comment]
@webdif The plugin will not append to an existing js file (it doesn't try to, but it might overwrite your actual app.js). Usually you would want to create a modernizr.js that you can add to your <head>.

Try changing to this and looking for `js/modernizr.js` in your public dir.

``` coffee
plugins:
        modernizr:
            destination: 'js/modernizr.js'
            tests: [
                'csscalc'
                'cssanimations'
                'csstransforms3d'
            ]
```

If you still have problems could you provide some more information please? (node version, brunch version, OS, etc).

**Comment by webdif** [comment]
OK, I misunderstood. Thanks!

**Comment by ianllewellyn** [comment]
Great! There are two reasons it works like this:
1. The plugin works by scanning your generated js and css files to see what modernizr hooks you have actually used, so it probably wouldn't want to then modify one of those files. That means you _shouldn't_ need to list modernizr tests in your config.coffee like in your example - if you use a test somewhere in your code, then the plugin should find and add them for you automatically.
2. (The main reason) Usually you want to add modernizr.js to your <head> because of html5 shiv and classes added to <html> causing DOM paints if css has rendered before modernizr.js executes.
